### ISSUE TITLE
Psicrystal not working

### ISSUE THREAD

**Issue by Leaguescience** [Rughalt/D35E#614] opened 2021-06-22 10:23 UTC
also on top of it not working, the level tab on the class wont open
![psicrystal](https://user-images.githubusercontent.com/33700136/122908545-3cf57480-d322-11eb-88ce-3d88d0b0040f.PNG)

**Comment by Rughalt** [comment] 2021-06-23 04:17
Cannot reproduce this, created a new psicrystal gave the character psion class, and pricrystal automatically leveled up and got health points. In this case, it's probably because psicrystal should be linked to the actor, and is bugged in that regard. This will be fixed in an upcoming update.

**Closed by Rughalt** 2021-06-23 04:17 UTC
Labels: Bug
