### ISSUE TITLE
horse riding skill little bug

### ISSUE THREAD

**Issue by Dany-Deaneris** [Rughalt/D35E#341] opened 2021-02-13 05:07 UTC
''riding'' have armor check penalty ?  If i look inside the rulebook it's not supposed to have it.

Not a big deal everyone can remove it manually but i wanted to point it out.

Oups wanted to remove this one, sorry for double post.

**Comment by Rughalt** [comment] 2021-02-13 06:00
Duplicate of #342

**Closed by Rughalt** 2021-02-13 06:00 UTC
Labels: Duplicate
