### ISSUE TITLE
Mage's Disjunction not marked as domain spell when added as such

### ISSUE THREAD

**Issue by wmve** [Rughalt/D35E#810] opened 2021-11-02 23:43 UTC
steps to reproduce

- create character
- add cleric class to character sheet
- add magic domain 
- open domain from sheet, click "add domain spells to spellbook"
- examine spell list
- note the following

![image](https://user-images.githubusercontent.com/55966777/139966513-8ee9bb04-3b05-497d-a26d-6f1f7fc46921.png)

expected behaviour: Mage's Disjunction marked with green star
actual behaviour: Mage's Disjunction NOT marked with green star

i wonder if there are other spells with this problem.  i don't know of any right now.

**Comment by wmve** [comment] 2021-11-02 23:46
i poked around but couldn't find a switch for toggling this as a "domain spell" manually.  sorry if i've forgotten where this is, other than listing it in the domain object.

**Comment by wmve** [comment] 2021-11-02 23:52
the other weird thing is that i don't have the link for "add all known class spells for this level" for 9th level.  but it's there for 8th lvl.

![image](https://user-images.githubusercontent.com/55966777/139967283-5e40065b-378a-4583-8247-aa5b5ba53db6.png)

**Comment by Rughalt** [comment] 2022-01-01 10:26
This was caused by the name being normalized and incorrectly checked. Will be fixed 0.99

**Closed by Rughalt** 2022-01-01 10:26 UTC
Labels: Bug
