### ISSUE TITLE
Buffs activated from chat apply to actor master sheets, not their unlinked tokens

### ISSUE THREAD

**Issue by freeformline** [Rughalt/D35E#330] opened 2021-02-06 09:11 UTC
On version 0.88.7, buffs created by SRD abilities such as Rage and Defensive Stance that are activated as a special attack, then applied by clicking on a tile in chat, are applying to the actor's master sheet (the one found in the actor directory) rather than to the token on the battlefield from which the power was activated. This is true only when the token is not linked to its master actor. When it is linked, the buff is applied correctly. 

Oddly, this problem manifests differently on a similar power I made myself. This power, which uses the same special action commands as the Defensive Stance power found in the system compendiums but refers to a custom buff in a world compendium, applies itself correctly to the unlinked token, but also applies itself (as it should not) to the master sheet for that token in the actor's directory. Furthermore, deleting the buff from the master sheet also removes the buff from the unlinked token.

This bug applies to both PC and NPC actor types.

Dragging and dropping buffs onto the token sheet works as normal.

I did not experience this issue on 0.87.11, the system version I was using until today (February 6, 2021).

For reference, I noticed this bug while setting up several NPC Dwarven Defender tokens who are all made from a common actor sheet, but who should have their buff durations and other stats tracked separately.

I have attached one of the actors (ragetest) I used to test this issue, as well as the custom power (Power Surge) and the actor (Brother Andor Ironhammer) who uses it:
[fvtt-Item-Power_Surge.txt](https://github.com/Rughalt/D35E/files/5936529/fvtt-Item-Power_Surge.txt)
[fvtt-Item-Power_Surge_(feature).txt](https://github.com/Rughalt/D35E/files/5936531/fvtt-Item-Power_Surge_.feature.txt)
[fvtt-Actor-Brother_Andor_Ironhammer.txt](https://github.com/Rughalt/D35E/files/5936533/fvtt-Actor-Brother_Andor_Ironhammer.txt)

[fvtt-Actor-ragetest.txt](https://github.com/Rughalt/D35E/files/5936502/fvtt-Actor-ragetest.txt)

**Comment by Rughalt** [comment] 2021-02-08 20:01
It was caused by missing field in chat card - "self' buffs should now apply correctly, should be fixed in 0.89

**Closed by Rughalt** 2021-02-08 20:01 UTC
Labels: Bug
